version: "3.9"
services:
  postgres:
    container_name: template_postgres
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
        - ./postgres:/var/lib/postgresql/data
    restart: always


  backend:
    container_name: template_backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - "8080:8000"
    depends_on:
        - postgres
    restart: always
    volumes:
      - ./backend:/app

networks:
  default: